name: MissionManager
version: ${project.version}
main: net.kinoko2k.MissionManager
api-version: '1.21'
load: STARTUP
authors: [ Kinoko_2K ]
commands:
  daily:
    description: "タスクを管理するコマンド"
    usage: "/<command>"
  reloaddaily:
    description: "ミッションを再読み込みします。"
    usage: "/reloaddaily"
    permission: missionmanager.reload
permissions:
  missionmanager.reload:
    default: op
